画面サイズ取得のカスタムフック作成
yyamazaki1732/try-next pull request #2
Opened 2023-10-16 00:04 UTC by yyamazaki1732

## ~~変更~~ プルリクの概要

- 任意の画面サイズでリロードするコンポーネントを作成しました。
- 宮里さんに下記の点を見ていただきたいです。

　- 不必要なレンダリングが起きないか
　- 一般的な作法に則った記述ができているか（特にReact）

## なぜこの ~~変更~~ プルリクをするのか

- ReactとTypescriptを勉強しており、適切に記述できているか少し不安です。なので、宮里さんにご確認いただきたいと思ったからです。

## やったこと

####  カスタムフック（`getWindowSize`）の作成
- [x] 画面の縦横のサイズをuseStateで設定
- [x] useEffect内でuseStateを更新させる
- [x] useEffectの第二引数の配列を空（ `[]` ）に設定 → 初回レンダリング以外は、リサイズイベントでのみuseStateを更新させるため

####  カスタムフックを利用するコンポーネント（`reloadComponent`）の作成
- [x] `GetCurrentWidth()` で画面水平方向のサイズを取得し、`currentWidth` を作成
- [x] リロードさせる画面サイズを `BREAK_POINT`で設定
- [x] `mediaMatches` で、画面サイズの状況を把握
- [x] useEffect内でuseRefの条件式（`currentWidth === BREAK_POINT && once.current`）を追加 → 不要なレンダリングを避けるため

## 特に確認いただきたい点
 - reloadComponentのおいて、新しいcurrentWidthオブジェクトがresizeイベントが生じるたびに生成されます。これは避けられない現象なのかどうか見ていただきたいです。

>    /**
>    *
>    * @returns GetWindowSize()から取得した画面横幅の値
>    */
>   function GetCurrentWidth() {
>     const { width: currentWidth }: { width: number } = GetWindowSize();
>     return currentWidth;
>   }
> 
>   const currentWidth = GetCurrentWidth();

## 備考

- Next.jsでこのコードを記述してるため、Next.js特有の制約？もあると思います。

2023-10-16 02:02 UTC, kazuki-miyazato-anice requested changes
コメントの確認お願いします。
ちなみに、react-useという有名なフックライブラリがあるので、そちらの内部コードを参考にしてみるのも勉強になると思います。
https://github.com/streamich/react-use

2023-10-16 02:02 UTC, kazuki-miyazato-anice commented on src/components/pages/useState/reloadComponent.tsx
> +  const mediaMatches: boolean = currentWidth >= BREAK_POINT ? true : false;
これはcurrentWidthが変更されるたびに再計算されてしまいそうですが、大丈夫でしょうか？
一度だけ判定したい場合は、 useMemoで判定し、
currentWidthが変わるたびに判定したい場合は、hookとして切り出すのが良いかと思います。

2023-10-16 02:02 UTC, kazuki-miyazato-anice commented on src/components/pages/useState/reloadComponent.tsx
> +  }, [once]);
初回だけ実行したいのであれば、依存配列を空にすれば良いかと思ったのですが、ロジックの関係でしょうか？

2023-10-23 12:50 UTC, yyamazaki1732 commented on src/components/pages/useState/getWindowSize.tsx
> +export const GetWindowSize = () => {
`useWindowSize`に変更しました。
このnext.jsはマニュアルインストールしたので、ESLintが有効になってないです。
ESLintを有効にしてみます。

2023-10-23 12:52 UTC, yyamazaki1732 commented on src/components/pages/useState/reloadComponent.tsx
> +import { GetWindowSize } from "@/components/pages/useState/getWindowSize";
`import { useWindowSize, useMediaMatches } from "@/components/hooks/index";`
`hooks`フォルダを作成し、そこへカスタムフックを移動させました。
後述する`useMediaMatches`というカスタムフックも`hooks`フォルダにいれ、エントリーポイントを作成しました。

2023-10-23 12:55 UTC, yyamazaki1732 commented on src/components/pages/useState/reloadComponent.tsx
> +  const currentWidth = GetCurrentWidth();
` const { width: currentWidth } = useWindowSize();`
上記のコードに修正しました。

JS Docコメントの`@return`を使用したかったので、無駄な関数を記述してしまいました。

2023-10-23 12:59 UTC, yyamazaki1732 commented on src/components/pages/useState/reloadComponent.tsx
> +  }, [once]);
`BREAK_POINT`を跨ぐたびに、コンポーネントをリロードさせたいです。
なので、`useRef`を用いて定義した`once`を依存配列に収めました。

2023-10-23 13:13 UTC, yyamazaki1732 commented
ご確認とコメントをいただきありがとうございます。

> ちなみに、react-useという有名なフックライブラリがあるので、そちらの内部コードを参考にしてみるのも勉強になると思います。
https://github.com/streamich/react-use

こちら、勉強する際、参考にしてみます。

resolvedになっていないコードが三つあります。
こちらに関して、修正したコードを再度、ご確認いただきたいです。
よろしくお願いいたします。

githubの機能やコードレビュー依頼側の作法を知らず、探り探りでお返事したので、見にくくなってしまっていたらすみません。

2023-10-24 02:46 UTC, kazuki-miyazato-anice commented on src/components/hooks/index.tsx
> +export {default as useWindowSize} from "@/components/hooks/useWindowSize";
```suggestion
export * from "@/components/hooks/useMediaMatches";
export * from "@/components/hooks/useWindowSize";
```
defaultに名前を付けるのであれば、named export した方がコードが簡潔になるかと思います。

2023-10-24 02:53 UTC, kazuki-miyazato-anice commented on src/components/pages/useState/reloadComponent.tsx
> +import { useWindowSize, useMediaMatches } from "@/components/hooks/index";
```suggestion
import { useWindowSize, useMediaMatches } from "@/components/hooks";
```
`index` は省略できます。

2023-10-24 03:01 UTC, kazuki-miyazato-anice reviewed
コメント確認お願いします。

2023-11-13 12:37 UTC, merged